name: Container Agent Docker Image CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'charts/**'
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read
      actions: read
      security-events: write
    env:
      REGISTRY: ghcr.io
      GH_URL: https://github.com

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file:  ./Dockerfile
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest
          labels: ${{ steps.metadata.outputs.labels }}
          push: true